### ISSUE TITLE
cgo import ?

### ISSUE THREAD

**Issue by flibustenet** [mattn/go-adodb#26]
In go-ole we can read that it doesn't use cgo.
I wonder if go-adodb still need cgo and a c compiler on windows ?
I'm worried with the "issue that your apps crash", what does it mean ? Could the readme be more precise about this ?
Thanks

**Comment by mattn** [comment]
See https://github.com/mattn/go-adodb/issues/14

But I don't reproduce this. So I don't know what should do.

**Comment by flibustenet** [comment]
Don't reproduce the problem myself.
