### ISSUE TITLE
List of tables and fields

### ISSUE THREAD

**Issue by flibustenet** [mattn/go-adodb#32]
Hi,

I'm looking for a way to extract tables and fields of a MSAccess database without making query. I wonder if go-adodb can help me for that or if i should look at go-ole ? (i'm not very confortable with windows api)
Maybe there is an example for this ?

Thanks

**Comment by mattn** [comment]
I'm not sure but could you please try this?

```sql
SELECT MSysObjects.Type, MSysObjects.Name, MSysObjects.Flags 
FROM MSysObjects 
where MSysObjects.Flags=0 AND Type=1 
ORDER BY MSysObjects.Type, MSysObjects.Name;
```

**Comment by flibustenet** [comment]
It said insufficient permissions, it's why i think i need to use ado directly

**Comment by flibustenet** [comment]
Will look at ado documentation directly
